FROM docker.io/library/ruby:3.1.2
COPY Gemfile Gemfile.lock /usr/src/app
COPY lib /usr/src/app/lib
COPY spec /usr/src/app/spec
WORKDIR /usr/src/app
RUN bundle install
RUN bundle exec standardrb
CMD ["bundle", "exec", "rspec", "spec"]
