name: Build on release

on:
  release:
    types: [ 'released' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
        - indicator
        - monitor
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.app }}
        file: Containerfile.serve
        push: true
        tags: |
          ghcr.io/mlibrary/kubernetes-network-test-${{ matrix.app }}:latest
          ghcr.io/mlibrary/kubernetes-network-test-${{ matrix.app }}:${{ github.event.release.tag_name }}
