name: Build latest from main

on:
  workflow_run:
    workflows: [ 'Tests' ]
    branches: [ 'main' ]
    types: [ 'completed' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
        - indicator
        - monitor
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.app }}
        file: ${{ matrix.app }}/Containerfile.serve
        push: true
        tags: |
          ghcr.io/mlibrary/kubernetes-network-test-${{ matrix.app }}-unstable:latest
          ghcr.io/mlibrary/kubernetes-network-test-${{ matrix.app }}-unstable:${{ github.sha }}
