name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-suite:
    name: Run suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
        - indicator
        - monitor
        - features
    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      if: ${{ matrix.app != 'features' }}
      run: |
        cd ${{ matrix.app }}
        podman build --tag test --file Containerfile.test .
        podman start --attach `podman create test`
    - name: Setup BATS
      uses: mig4/setup-bats@v1
      if: ${{ matrix.app == 'features' }}
    - name: Run end-to-end tests
      if: ${{ matrix.app == 'features' }}
      run: |
        bats features.bats
